/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HousesRouteRouteImport } from './routes/houses/route'
import { Route as HousesIndexRouteImport } from './routes/houses/index'
import { Route as HousesIdRouteImport } from './routes/houses/$id'
import { Route as ApiHousesIndexRouteImport } from './routes/api/houses/index'
import { Route as ApiHousesIdRouteImport } from './routes/api/houses/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRouteRoute = HousesRouteRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HousesRouteRoute,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HousesRouteRoute,
} as any)
const ApiHousesIndexRoute = ApiHousesIndexRouteImport.update({
  id: '/api/houses/',
  path: '/api/houses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHousesIdRoute = ApiHousesIdRouteImport.update({
  id: '/api/houses/$id',
  path: '/api/houses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/houses': typeof HousesRouteRouteWithChildren
  '/houses/$id': typeof HousesIdRoute
  '/houses/': typeof HousesIndexRoute
  '/api/houses/$id': typeof ApiHousesIdRoute
  '/api/houses/': typeof ApiHousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/houses/$id': typeof HousesIdRoute
  '/houses': typeof HousesIndexRoute
  '/api/houses/$id': typeof ApiHousesIdRoute
  '/api/houses': typeof ApiHousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/houses': typeof HousesRouteRouteWithChildren
  '/houses/$id': typeof HousesIdRoute
  '/houses/': typeof HousesIndexRoute
  '/api/houses/$id': typeof ApiHousesIdRoute
  '/api/houses/': typeof ApiHousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/houses'
    | '/houses/$id'
    | '/houses/'
    | '/api/houses/$id'
    | '/api/houses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/houses/$id' | '/houses' | '/api/houses/$id' | '/api/houses'
  id:
    | '__root__'
    | '/'
    | '/houses'
    | '/houses/$id'
    | '/houses/'
    | '/api/houses/$id'
    | '/api/houses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HousesRouteRoute: typeof HousesRouteRouteWithChildren
  ApiHousesIdRoute: typeof ApiHousesIdRoute
  ApiHousesIndexRoute: typeof ApiHousesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof HousesRouteRoute
    }
    '/houses/$id': {
      id: '/houses/$id'
      path: '/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof HousesRouteRoute
    }
    '/api/houses/': {
      id: '/api/houses/'
      path: '/api/houses'
      fullPath: '/api/houses/'
      preLoaderRoute: typeof ApiHousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/houses/$id': {
      id: '/api/houses/$id'
      path: '/api/houses/$id'
      fullPath: '/api/houses/$id'
      preLoaderRoute: typeof ApiHousesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HousesRouteRouteChildren {
  HousesIdRoute: typeof HousesIdRoute
  HousesIndexRoute: typeof HousesIndexRoute
}

const HousesRouteRouteChildren: HousesRouteRouteChildren = {
  HousesIdRoute: HousesIdRoute,
  HousesIndexRoute: HousesIndexRoute,
}

const HousesRouteRouteWithChildren = HousesRouteRoute._addFileChildren(
  HousesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HousesRouteRoute: HousesRouteRouteWithChildren,
  ApiHousesIdRoute: ApiHousesIdRoute,
  ApiHousesIndexRoute: ApiHousesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
